import { Tool } from './types';

export const TOOLS: Tool[] = [
  // Módulo: Ajustes Essenciais
  {
    id: 'quick-adjust',
    module: 'Ajustes Essenciais',
    icon: 'tune',
    name: 'Ajustes Rápidos',
    description: 'Ajuste rapidamente o brilho, contraste e sombras da sua imagem.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'adjust-colors',
    module: 'Ajustes Essenciais',
    icon: 'settings',
    name: 'Cor e Luz (Avançado)',
    description: 'Ajuste brilho, contraste, saturação e mais.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'resize',
    module: 'Ajustes Essenciais',
    icon: 'crop',
    name: 'Redimensionar',
    description: 'Altere a largura e altura da imagem.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'sharpness',
    module: 'Ajustes Essenciais',
    icon: 'search',
    name: 'Nitidez',
    description: 'Aplica um filtro de nitidez com 30% de intensidade para realçar detalhes finos. Ajuste a intensidade conforme necessário.',
    promptSuggestion: '',
    isManualControl: true,
  },
  
  // Módulo: Beleza (IA)
  {
    id: 'ia-beauty-retouch',
    module: 'Beleza (IA)',
    icon: 'face',
    name: 'Retoques de Beleza',
    description: 'Aplique retoques de beleza e reparos na compleição, rugas, barba e cabelo, sem alterar as feições do rosto.',
    promptSuggestion: 'Use os controles abaixo para aplicar retoques de beleza.',
    isManualControl: true,
  },
  {
    id: 'ia-age-machine',
    module: 'Beleza (IA)',
    icon: 'clock',
    name: 'Máquina do Tempo',
    description: 'Envelheça ou rejuvenesça uma pessoa na foto. Use a "Seleção Livre" para focar em um rosto específico.',
    promptSuggestion: '',
    isManualControl: false, // Controlado por um painel customizado
  },
  {
    id: 'ia-body-weight',
    module: 'Beleza (IA)',
    icon: 'weight',
    name: 'Emagrecer / Engordar',
    description: 'Ajuste o peso corporal da pessoa na foto. Use a "Seleção Livre" para focar em uma pessoa específica.',
    promptSuggestion: '',
    isManualControl: false,
  },
  {
    id: 'ia-face-swap',
    module: 'Beleza (IA)',
    icon: 'swap',
    name: 'Troca de Rosto',
    description: 'Selecione um rosto na foto e use uma imagem de referência para trocá-lo. A IA ajusta tom de pele, iluminação e ângulo.',
    promptSuggestion: 'troque o rosto selecionado pelo rosto da imagem de referência',
  },
  {
    id: 'ia-combine-people',
    module: 'Beleza (IA)',
    icon: 'person-add',
    name: 'Juntar Pessoas',
    description: 'Adicione uma pessoa de uma imagem de referência à sua foto principal. Descreva onde ela deve aparecer.',
    promptSuggestion: 'adicione a pessoa da imagem de referência sentada no sofá, sorrindo',
  },
  {
    id: 'ia-poses-expressions',
    module: 'Beleza (IA)',
    icon: 'body-pose',
    name: 'Poses e Expressões',
    description: 'Mude a expressão facial ou a pose corporal de uma pessoa usando texto. Use a "Seleção Livre" para focar em uma pessoa.',
    promptSuggestion: 'mude a expressão para um sorriso feliz',
    promptExamples: ['faça a pessoa olhar para a câmera', 'mude a pose para estar com os braços cruzados', 'altere a expressão para surpresa'],
  },
  
  // Módulo: Edição Mágica (IA)
  {
    id: 'ia-selection',
    module: 'Edição Mágica (IA)',
    icon: 'selection',
    name: 'Seleção Livre',
    description: 'Desenhe para selecionar uma área onde a IA deve atuar.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'ia-analyze-photo',
    module: 'Edição Mágica (IA)',
    icon: 'search',
    name: 'Analisador de Fotos',
    description: 'Deixe a IA analisar sua foto e sugerir melhorias de iluminação, cor, enquadramento e mais.',
    promptSuggestion: '',
    isManualControl: false,
  },
  {
    id: 'ia-remove-object',
    module: 'Edição Mágica (IA)',
    icon: 'eraser',
    name: 'Remover Objeto',
    description: 'Use a ferramenta "Seleção Livre" para marcar um objeto e a IA o removerá perfeitamente.',
    promptSuggestion: 'Remova o objeto selecionado',
    promptExamples: ['remova a pessoa de camisa vermelha', 'apague o carro estacionado', 'elimine o texto da imagem'],
  },
  {
    id: 'ia-remove-background',
    module: 'Edição Mágica (IA)',
    icon: 'scissors',
    name: 'Fundo Transparente',
    description: 'Remove o fundo da imagem e o torna transparente, mantendo o objeto principal com bordas perfeitas.',
    promptSuggestion: 'Identifique o objeto ou pessoa principal em primeiro plano. Crie uma máscara de recorte precisa ao redor dele. Remova todo o fundo, tornando-o totalmente transparente (formato PNG com canal alfa). O resultado deve ser apenas o objeto principal isolado com bordas suaves e perfeitas.',
    oneClick: true,
  },
  {
    id: 'ia-change-background',
    module: 'Edição Mágica (IA)',
    icon: 'background',
    name: 'Alterar Fundo',
    description: 'Substitui o fundo por um cenário descrito ou baseado em uma imagem de referência.',
    promptSuggestion: 'um cenário de praia ensolarada com palmeiras e um mar azul cristalino',
    promptExamples: ['floresta encantada com luzes mágicas', 'cidade cyberpunk à noite', 'fundo de estúdio fotográfico branco'],
  },
  {
    id: 'ia-background-blur',
    module: 'Edição Mágica (IA)',
    icon: 'aperture',
    name: 'Foco de Retrato',
    description: 'Aplica um efeito de foco de retrato, ajustando a intensidade do desfoque para manter o assunto principal nítido.',
    promptSuggestion: 'Aplique um efeito de foco de retrato com 75% de intensidade de desfoque, mantendo o assunto principal nítido',
  },
  {
    id: 'ia-tattoo-artist',
    module: 'Edição Mágica (IA)',
    icon: 'tattoo',
    name: 'Tatuador de IA',
    description: 'Adicione tatuagens realistas a partir de texto ou de uma imagem de referência.',
    promptSuggestion: 'adicione uma tatuagem de dragão no braço direito',
    promptExamples: ['tatuagem de uma rosa no ombro', 'uma pequena fênix no pulso', 'tatuagem maori na perna'],
  },
  {
    id: 'ia-steal-clothes',
    module: 'Edição Mágica (IA)',
    icon: 'shirt',
    name: 'Rouba Roupa',
    description: 'Pegue a roupa de uma pessoa em uma foto de referência e vista na pessoa da sua foto principal.',
    promptSuggestion: 'troque a roupa da pessoa pela roupa da imagem de referência',
    promptExamples: ['vista a pessoa com a jaqueta de couro da foto de referência', 'copie o vestido da imagem de referência', 'troque a camisa pela camiseta da outra foto'],
  },
  {
    id: 'ia-improve-quality',
    module: 'Edição Mágica (IA)',
    icon: 'sparkles',
    name: 'Melhorar Qualidade',
    description: 'Aumenta a nitidez, remove ruído e melhora a iluminação.',
    promptSuggestion: 'melhore a iluminação e a nitidez da foto',
    oneClick: true,
  },
  {
    id: 'ia-refine-details',
    module: 'Edição Mágica (IA)',
    icon: 'search',
    name: 'Refinar Detalhes',
    description: 'Usa IA para realçar detalhes finos, aumentando a nitidez e a clareza geral da imagem.',
    promptSuggestion: 'Refine os detalhes finos da imagem, melhorando a nitidez e a textura.',
    oneClick: false,
    promptExamples: ['realce a textura do tecido', 'aumente a nitidez dos olhos', 'defina melhor os detalhes da arquitetura'],
  },
  {
    id: 'ia-night-mode',
    module: 'Edição Mágica (IA)',
    icon: 'night-mode',
    name: 'Melhorar Iluminação Noturna',
    description: 'Melhora a clareza, brilho e cores de fotos tiradas em baixa luminosidade.',
    promptSuggestion: 'Ajuste esta foto noturna para melhorar a iluminação, reduzir o ruído e realçar os detalhes nas áreas escuras, como se tivesse sido tirada com uma câmera profissional.',
    oneClick: true,
  },
  {
    id: 'ia-stabilize-shake',
    module: 'Edição Mágica (IA)',
    icon: 'deblur',
    name: 'Estabilização de Tremido',
    description: 'Usa IA para corrigir fotos borradas por movimento ou trepidação da câmera.',
    promptSuggestion: 'Analise e corrija a imagem para remover o desfoque causado by trepidação da câmera, aumentando a nitidez e a definição dos contornos.',
    oneClick: true,
  },
  {
    id: 'ia-stylize',
    module: 'Edição Mágica (IA)',
    icon: 'brush',
    name: 'Estilizar Imagem',
    description: 'Transforma a foto em um estilo artístico específico.',
    promptSuggestion: 'transforme em uma pintura a óleo',
    predefinedStyles: [
      { name: 'Aquarela', prompt: 'transforme a imagem em uma pintura de aquarela com cores vibrantes' },
      { name: 'Desenho a Lápis', prompt: 'transforme a imagem em um desenho a lápis de grafite detalhado com hachuras' },
      { name: 'Óleo Sobre Tela', prompt: 'transforme a imagem em uma pintura a óleo sobre tela com pinceladas visíveis' },
      { name: 'Pixel Art', prompt: 'transforme a imagem em pixel art estilo 16-bit' },
      { name: 'Cyberpunk Neon', prompt: 'transforme a imagem para o estilo cyberpunk, com luzes de neon brilhantes, cores vibrantes como rosa e ciano, e uma atmosfera urbana futurista' },
      { name: 'Filme Vintage', prompt: 'transforme a imagem para parecer uma fotografia de filme antigo, com granulação visível, cores ligeiramente desbotadas e um tom quente' },
      { name: 'Expressionismo', prompt: 'transforme a imagem em uma pintura expressionista abstrata, com pinceladas gestuais e cores ousadas' },
      { name: 'HQ Vintage', prompt: 'converta a imagem para o estilo de uma história em quadrinhos vintage, com contornos pretos fortes e meio-tom' },
      { name: 'Desenho Animado', prompt: 'transforme a imagem em um desenho animado 2D com cores vibrantes e contornos pretos definidos, estilo animação clássica' },
      { name: 'Arte Vetorial', prompt: 'converta a imagem em uma arte vetorial minimalista, com formas geométricas simples e uma paleta de cores limitada' },
      { name: 'Foco Cinematográfico', prompt: 'aplique um efeito de profundidade de campo cinematográfica, desfocando o fundo (efeito bokeh) e mantendo o assunto principal em foco nítido' },
      { name: 'Arte Cubista', prompt: 'transforme a imagem em uma pintura cubista, com formas geométricas fragmentadas e múltiplas perspectivas' },
      { name: 'Arte Pixelada Retrô', prompt: 'transforme a imagem em arte pixelada com tema retrô, paleta de cores limitada e estilo de 8-bits' },
      { name: 'Pintura Impressionista', prompt: 'transforme a imagem em uma pintura impressionista com pinceladas curtas e visíveis, focando na luz e em tons pastéis' },
      { name: 'Ilustração Vetorial Futurista', prompt: 'transforme a imagem em uma ilustração vetorial de paisagem futurista, com linhas limpas, formas geométricas e gradientes suaves' },
    ],
  },

  // Módulo: Filtros com IA
  {
    id: 'ia-filter-sketch',
    module: 'Filtros com IA',
    icon: 'brush',
    name: 'Esboço a Lápis',
    description: 'Transforma a foto em um desenho a lápis de grafite.',
    promptSuggestion: 'transforme a imagem em um desenho a lápis de grafite detalhado com hachuras',
    oneClick: true,
  },
  {
    id: 'ia-filter-cartoon',
    module: 'Filtros com IA',
    icon: 'sparkles',
    name: 'Efeito Cartoon',
    description: 'Converte a foto para um estilo de desenho animado.',
    promptSuggestion: 'transforme a imagem em um desenho animado 2D com cores vibrantes e contornos pretos definidos, estilo animação clássica',
    oneClick: true,
  },
  {
    id: 'ia-filter-oil-painting',
    module: 'Filtros com IA',
    icon: 'palette',
    name: 'Pintura a Óleo',
    description: 'Aplica um efeito de pintura a óleo na imagem.',
    promptSuggestion: 'transforme a imagem em uma pintura a óleo sobre tela com pinceladas visíveis',
    oneClick: true,
  },
  {
    id: 'ia-filter-watercolor',
    module: 'Filtros com IA',
    icon: 'droplet',
    name: 'Aquarela',
    description: 'Converte a foto para uma pintura em aquarela.',
    promptSuggestion: 'transforme a imagem em uma pintura de aquarela com cores vibrantes e bordas suaves',
    oneClick: true,
  },
  {
    id: 'ia-filter-pixel-art',
    module: 'Filtros com IA',
    icon: 'square',
    name: 'Pixel Art',
    description: 'Converte a foto para o estilo pixel art.',
    promptSuggestion: 'transforme a imagem em pixel art estilo 16-bit',
    oneClick: true,
  },
  {
    id: 'ia-filter-cyberpunk',
    module: 'Filtros com IA',
    icon: 'zap',
    name: 'Cyberpunk',
    description: 'Aplica um estilo cyberpunk com luzes de neon.',
    promptSuggestion: 'transforme a imagem para o estilo cyberpunk, com luzes de neon brilhantes, cores vibrantes como rosa e ciano, e uma atmosfera urbana futurista',
    oneClick: true,
  },
  {
    id: 'ia-filter-vintage-comic',
    module: 'Filtros com IA',
    icon: 'palette',
    name: 'HQ Vintage',
    description: 'Converte a foto para um estilo de quadrinhos retrô.',
    promptSuggestion: 'converta a imagem para o estilo de uma história em quadrinhos vintage, com contornos pretos fortes e meio-tom',
    oneClick: true,
  },
  {
    id: 'ia-filter-vintage-film',
    module: 'Filtros com IA',
    icon: 'camera',
    name: 'Filme Vintage',
    description: 'Simula a aparência de uma fotografia de filme antigo.',
    promptSuggestion: 'transforme a imagem para parecer uma fotografia de filme antigo, com granulação visível, cores ligeiramente desbotadas e um tom quente',
    oneClick: true,
  },
  {
    id: 'ia-filter-vector-art',
    module: 'Filtros com IA',
    icon: 'layers',
    name: 'Arte Vetorial',
    description: 'Converte a foto em uma arte vetorial minimalista.',
    promptSuggestion: 'converta a imagem em uma arte vetorial minimalista, com formas geométricas simples e uma paleta de cores limitada',
    oneClick: true,
  },
  {
    id: 'ia-filter-cubism',
    module: 'Filtros com IA',
    icon: 'square',
    name: 'Arte Cubista',
    description: 'Recria a imagem no estilo cubista, com formas geométricas e múltiplas perspectivas.',
    promptSuggestion: 'transforme a imagem em uma pintura cubista, com formas geométricas fragmentadas e múltiplas perspectivas',
    oneClick: true,
  },
  {
    id: 'ia-filter-chalk-drawing',
    module: 'Filtros com IA',
    icon: 'brush',
    name: 'Desenho de Giz',
    description: 'Converte a foto para um desenho de giz colorido sobre um quadro-negro.',
    promptSuggestion: 'transforme a imagem para parecer um desenho de giz colorido sobre uma lousa escura',
    oneClick: true,
  },
  {
    id: 'ia-filter-golden',
    module: 'Filtros com IA',
    icon: 'sparkles',
    name: 'Dourado',
    description: 'Aplica um efeito dourado e brilhante, realçando os destaques da imagem.',
    promptSuggestion: 'aplique um efeito dourado luxuoso à imagem, transformando os realces em ouro brilhante e adicionando um brilho mágico',
    oneClick: true,
  },

  // Módulo: Lar & Decoração (IA)
  {
    id: 'ia-interior-decorator',
    module: 'Lar & Decoração (IA)',
    icon: 'home',
    name: 'Decorador IA',
    description: 'Redecore um cômodo com base em estilos (ex: moderno, rústico).',
    promptSuggestion: 'redecore esta sala em um estilo minimalista com tons neutros',
    promptExamples: ['transforme esta sala em um estilo industrial com parede de tijolos', 'decore o quarto com tema espacial para crianças', 'mude para um estilo boho com muitas plantas e texturas naturais'],
  },
  {
    id: 'ia-color-visualizer',
    module: 'Lar & Decoração (IA)',
    icon: 'palette',
    name: 'Pintor Virtual',
    description: 'Teste diferentes cores de parede em seu ambiente.',
    promptSuggestion: 'pinte a parede principal de azul marinho',
    promptExamples: ['pinte todas as paredes de um verde sálvia suave', 'crie uma parede de destaque com a cor terracota', 'pinte o teto de preto'],
  },
  {
    id: 'ia-virtual-furniture',
    module: 'Lar & Decoração (IA)',
    icon: 'package',
    name: 'Móveis Virtuais',
    description: 'Adicione, remova ou troque móveis no seu ambiente.',
    promptSuggestion: 'adicione um sofá de couro marrom no centro da sala',
    promptExamples: ['remova a mesa de centro', 'troque a cadeira por uma poltrona moderna amarela', 'adicione uma estante de livros na parede de trás'],
  },
  {
    id: 'ia-magic-lighting',
    module: 'Lar & Decoração (IA)',
    icon: 'improve-lighting',
    name: 'Iluminação Mágica',
    description: 'Altere a iluminação do ambiente para criar um clima diferente.',
    promptSuggestion: 'mude a iluminação para uma luz quente de pôr do sol entrando pela janela',
    promptExamples: ['iluminação de velas romântica', 'luz neon colorida para uma festa', 'luz do dia clara e brilhante'],
  },
  {
    id: 'ia-window-view',
    module: 'Lar & Decoração (IA)',
    icon: 'image',
    name: 'Vista da Janela',
    description: 'Mude a paisagem vista através das janelas.',
    promptSuggestion: 'mude a vista da janela para uma paisagem de montanhas nevadas',
    promptExamples: ['uma cidade futurista à noite', 'uma floresta tropical densa', 'uma praia paradisíaca'],
  },
  {
    id: 'ia-room-organizer',
    module: 'Lar & Decoração (IA)',
    icon: 'sparkles',
    name: 'Organizador de Ambientes',
    description: 'Arruma um cômodo bagunçado com um toque de mágica.',
    promptSuggestion: 'arrume toda a bagunça neste quarto, organizando os objetos de forma limpa e minimalista',
    oneClick: true,
  },
  {
    id: 'ia-food-enhancer',
    module: 'Lar & Decoração (IA)',
    icon: 'camera',
    name: 'Mestre Cuca IA',
    description: 'Melhora a aparência de pratos, tornando-os mais apetitosos.',
    promptSuggestion: 'faça este prato parecer mais vibrante e delicioso, como em uma revista de culinária',
    oneClick: true,
  },

  // Módulo: Salão de Beleza (IA)
  {
    id: 'ia-virtual-makeup',
    module: 'Salão de Beleza (IA)',
    icon: 'makeup-brush',
    name: 'Maquiagem IA',
    description: 'Aplique estilos de maquiagem, do natural ao glamouroso.',
    promptSuggestion: 'aplique uma maquiagem de festa com batom vermelho e olhos esfumados',
    promptExamples: ['maquiagem leve para o dia a dia', 'maquiagem gótica com batom preto', 'sombra com glitter dourado'],
  },
  {
    id: 'ia-hairstyle-tryon',
    module: 'Salão de Beleza (IA)',
    icon: 'hair',
    name: 'Penteado Virtual',
    description: 'Experimente diferentes penteados e cortes de cabelo.',
    promptSuggestion: 'adicione um corte de cabelo chanel com franja',
    promptExamples: ['cabelo longo e ondulado', 'um coque alto elegante', 'corte de cabelo pixie ousado'],
  },
  {
    id: 'ia-eye-color-changer',
    module: 'Salão de Beleza (IA)',
    icon: 'eye-color',
    name: 'Cor dos Olhos',
    description: 'Mude a cor dos olhos da pessoa na foto.',
    promptSuggestion: 'mude a cor dos olhos para verde esmeralda',
    promptExamples: ['olhos azuis vibrantes', 'olhos cor de mel', 'olhos violeta fantasia'],
  },
  {
    id: 'ia-teeth-whitening',
    module: 'Salão de Beleza (IA)',
    icon: 'teeth',
    name: 'Clarear Dentes',
    description: 'Deixe os dentes mais brancos e brilhantes com um clique.',
    promptSuggestion: 'clareie os dentes da pessoa de forma natural e realista',
    oneClick: true,
  },
  {
    id: 'ia-nail-art',
    module: 'Salão de Beleza (IA)',
    icon: 'hand',
    name: 'Nail Art IA',
    description: 'Crie e visualize designs de unhas artísticas.',
    promptSuggestion: 'adicione unhas artísticas com um design de galáxia',
    promptExamples: ['unhas francesinhas clássicas', 'unhas cromadas em prata', 'nail art com pequenas flores'],
  },
  {
    id: 'ia-remove-unwanted-hair',
    module: 'Salão de Beleza (IA)',
    icon: 'razor',
    name: 'Remover Pelos',
    description: 'Remove pelos indesejados do rosto ou corpo, proporcionando uma pele lisa.',
    promptSuggestion: 'remova os pelos faciais de forma natural e suave',
    oneClick: true,
  },

  // Módulo: Arquitetura & Design (IA)
  {
    id: 'ia-architectural-sketch',
    module: 'Arquitetura & Design (IA)',
    icon: 'ruler',
    name: 'Esboço de Arquiteto',
    description: 'Transforme a foto de um edifício em um esboço técnico ou artístico.',
    promptSuggestion: 'converta a foto desta fachada em um esboço de arquitetura a caneta',
    oneClick: true,
  },
  {
    id: 'ia-material-changer',
    module: 'Arquitetura & Design (IA)',
    icon: 'layers',
    name: 'Troca de Materiais',
    description: 'Altere materiais de construção, como madeira, concreto ou vidro.',
    promptSuggestion: 'troque a parede de tijolos por uma parede de concreto aparente',
    promptExamples: ['mude o telhado para telhas de terracota', 'transforme as janelas em madeira escura', 'adicione um revestimento de pedra à base da casa'],
  },
  {
    id: 'ia-landscape-designer',
    module: 'Arquitetura & Design (IA)',
    icon: 'sparkles',
    name: 'Paisagismo IA',
    description: 'Adicione ou modifique jardins e áreas externas.',
    promptSuggestion: 'adicione um jardim florido com um caminho de pedras na frente da casa',
    promptExamples: ['crie um jardim de pedras zen', 'adicione uma grande árvore de carvalho no quintal', 'plante uma cerca viva ao redor da propriedade'],
  },
  
  // Módulo: Barbearia (IA)
  {
    id: 'ia-beard-styler',
    module: 'Barbearia (IA)',
    icon: 'beard',
    name: 'Estilista de Barba',
    description: 'Experimente diferentes estilos e cores de barba.',
    promptSuggestion: 'adicione uma barba cheia e bem aparada',
    promptExamples: ['adicione um bigode de guidão', 'faça uma barba por fazer (stubble)', 'adicione um cavanhaque'],
  },
  {
    id: 'ia-beard-color',
    module: 'Barbearia (IA)',
    icon: 'droplet',
    name: 'Cor da Barba',
    description: 'Mude a cor da barba para qualquer tom que desejar.',
    promptSuggestion: 'mude a cor da barba para ruivo',
    promptExamples: ['barba grisalha', 'barba preta intensa', 'barba loira'],
  },
  {
    id: 'ia-clean-shave',
    module: 'Barbearia (IA)',
    icon: 'razor',
    name: 'Barba Limpa',
    description: 'Remova a barba e o bigode para um visual barbeado.',
    promptSuggestion: 'remova completamente a barba e o bigode do rosto da pessoa, deixando a pele lisa',
    oneClick: true,
  },
  {
    id: 'ia-haircut-simulator',
    module: 'Barbearia (IA)',
    icon: 'scissors',
    name: 'Corte de Cabelo IA',
    description: 'Visualize novos cortes de cabelo masculinos.',
    promptSuggestion: 'mude o corte de cabelo para um estilo militar (buzz cut)',
    promptExamples: ['corte de cabelo pompadour', 'cabelo comprido e amarrado em um coque', 'corte de cabelo com fade nas laterais'],
  },
  
  // Módulo: Efeitos Criativos
  {
    id: 'color-balance',
    module: 'Efeitos Criativos',
    icon: 'droplet',
    name: 'Balanço de Cores',
    description: 'Ajuste as cores em sombras, tons médios e realces.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'color-palette',
    module: 'Efeitos Criativos',
    icon: 'palette',
    name: 'Paleta de Cores',
    description: 'Analisa as cores da imagem e sugere paletas harmoniosas.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'filters',
    module: 'Efeitos Criativos',
    icon: 'aperture',
    name: 'Filtros Artísticos',
    description: 'Aplique filtros como Sépia e Vintage.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'duotone',
    module: 'Efeitos Criativos',
    icon: 'palette',
    name: 'Duotono',
    description: 'Cria um efeito de duas cores na imagem com cores e intensidade customizáveis.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'gradient-filter',
    module: 'Efeitos Criativos',
    icon: 'layers',
    name: 'Gradação Linear',
    description: 'Aplica um gradiente suave por padrão. Ajuste as cores e a intensidade conforme necessário.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'vignette',
    module: 'Efeitos Criativos',
    icon: 'vignette',
    name: 'Vinheta Escura',
    description: 'Aplica uma vinheta escura com intensidade de 70% e tamanho de 50% para focar no centro da imagem.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'frame',
    module: 'Efeitos Criativos',
    icon: 'square',
    name: 'Moldura',
    description: 'Adicione uma moldura customizável à sua imagem.',
    promptSuggestion: '',
    isManualControl: true,
  },
  {
    id: 'contour',
    module: 'Efeitos Criativos',
    icon: 'contour',
    name: 'Contorno',
    description: 'Realça as bordas e contornos da imagem.',
    promptSuggestion: '',
    isManualControl: true,
  },
  
  // Módulo: Criação com IA
  {
    id: 'ia-generate-image',
    module: 'Criação com IA',
    icon: 'zap',
    name: 'Gerar Imagem',
    description: 'Cria uma imagem a partir de uma descrição de texto.',
    promptSuggestion: 'Um golem colossal feito de rocha vulcânica e musgo luminoso, caminhando lentamente por uma floresta enevoada à noite. Runas antigas brilham em seu corpo com uma luz azul suave. Pequenos espíritos da floresta, como vagalumes, flutuam ao seu redor. A cena é iluminada pela lua cheia que atravessa as árvores altas. Estilo: fotografia cinematográfica, fotorrealista, lente de 85mm, iluminação dramática, alta resolução, 8k, octane render.',
    isGenerator: true,
    promptExamples: ['um astronauta surfando em um anel de Saturno', 'uma biblioteca antiga dentro de uma árvore gigante', 'um gato detetive em uma rua chuvosa de neon, estilo noir'],
  },
  {
    id: 'ia-logo-creator',
    module: 'Criação com IA',
    icon: 'logo',
    name: 'Criador de Logos',
    description: 'Crie um conceito de logo a partir de uma descrição de texto.',
    promptSuggestion: 'um logo minimalista para uma cafeteria chamada "Aroma Cósmico", com um grão de café e um planeta Saturno',
    promptExamples: ['logo de uma raposa em estilo origami para uma empresa de tecnologia', 'emblema vintage para uma barbearia com navalhas cruzadas', 'logo divertido com um cérebro levantando pesos para um app de fitness mental'],
    isGenerator: true,
  },
  {
    id: 'ia-pattern-generator',
    module: 'Criação com IA',
    icon: 'layers',
    name: 'Gerador de Padrões',
    description: 'Crie um padrão repetível (seamless pattern) a partir de uma descrição.',
    promptSuggestion: 'um padrão de azulejos hidráulicos portugueses em azul e branco',
    promptExamples: ['padrão de limões sicilianos e folhas em aquarela', 'padrão geométrico art déco dourado e preto', 'padrão fofo com gatos astronautas no espaço'],
    isGenerator: true,
  },
  {
    id: 'ia-generate-background',
    module: 'Criação com IA',
    icon: 'background',
    name: 'Gerar Fundo',
    description: 'Cria uma imagem de fundo a partir de texto para ser usada com a ferramenta "Alterar Fundo".',
    promptSuggestion: 'O interior de uma estufa biodomo em Marte ao amanhecer. Plantas bioluminescentes exóticas com tons de azul e roxo brilham suavemente. Através do teto de vidro curvo, é possível ver o céu marciano avermelhado e as estrelas. Um pequeno robô jardineiro paira silenciosamente, cuidando das plantas. Estilo: arte de conceito de ficção científica, sereno, iluminação suave e etérea, detalhado, Weta Digital, alta resolução.',
    isGenerator: true,
  },
  // Módulo: Construtor de Casas (IA)
  {
    id: 'ia-house-builder',
    module: 'Construtor de Casas (IA)',
    icon: 'home',
    name: 'Construtor de Casas',
    description: 'Projete ou modifique casas e edifícios em uma paisagem. Descreva o estilo, materiais e a integração com o ambiente da foto.',
    promptSuggestion: 'Adicione uma casa de fazenda moderna, com grandes janelas e um deck espaçoso, integrada à paisagem montanhosa existente.',
    promptExamples: ['construa uma cabana de madeira rústica na floresta', 'adicione um castelo medieval no topo da colina', 'projete um arranha-céu futurista na cidade'],
  },
  {
    id: 'ia-facade-renovation',
    module: 'Construtor de Casas (IA)',
    icon: 'home',
    name: 'Reforma de Fachada',
    description: 'Altere o estilo, as cores ou os materiais da fachada de um edifício.',
    promptSuggestion: 'mude a fachada para um estilo vitoriano com cores pastéis',
    promptExamples: ['fachada de madeira rústica', 'fachada moderna com concreto e vidro', 'pinte a casa de branco com janelas azuis'],
  },
  {
    id: 'ia-pool-designer',
    module: 'Construtor de Casas (IA)',
    icon: 'droplet',
    name: 'Design de Piscinas',
    description: 'Adicione uma piscina com paisagismo ao redor no quintal.',
    promptSuggestion: 'adicione uma piscina de borda infinita com um deck de madeira ao redor',
    promptExamples: ['piscina em formato de lagoa com pedras e plantas', 'piscina retangular com raia para natação', 'uma pequena piscina redonda com cascata'],
  },
];